In [1]:
import tensorflow as tf
print(tf.__version__)

2.1.0


In [2]:
from tensorflow import keras
print(keras.__version__)

2.2.4-tf


In [3]:
BATCH_SIZE = 128
NUM_CLASSES = 10
EPOCHS = 10
IMG_ROWS, IMG_COLS = 28,28

In [4]:
handwriten_number_names = ["0","1","2","3","4","5","6","7","8","9"]

In [5]:
mnist = tf.keras.datasets.mnist
(train_data, train_teacher_labels),(test_data,test_teacher_labels) = mnist.load_data()
print("ロードした後の学習データ　train_data shape: ",train_data.shape)
print("ロードした後の学習データ　test_data shape: ",test_data.shape)

ロードした後の学習データ　train_data shape:  (60000, 28, 28)
ロードした後の学習データ　test_data shape:  (10000, 28, 28)


In [6]:
Keras = tf.keras.backend
print("Channel調整前 train_data shape:", train_data.shape)
print("Channel調整前 test_data shape:", test_data.shape)
if Keras.image_data_format() == "channels_first":
    train_data = train_data.reshape(train_data.shape[0], 1, IMG_ROWS, IMG_COLS)
    test_data = test_data.reshape(test_data.shape[0], 1, IMG_ROWS, IMG_COLS)
    input_shape = (1, IMG_ROWS, IMG_COLS)
else:
    train_data = train_data.reshape(train_data.shape[0], IMG_ROWS, IMG_COLS, 1)
    test_data = test_data.reshape(test_data.shape[0], IMG_ROWS, IMG_COLS, 1)
    input_shape = (IMG_ROWS, IMG_COLS, 1)
print("Channel調整変換後　train_data shape: ",train_data.shape)
print("Channel調整変換後　test_data shape: ",test_data.shape)

Channel調整前 train_data shape: (60000, 28, 28)
Channel調整前 test_data shape: (10000, 28, 28)
Channel調整変換後　train_data shape:  (60000, 28, 28, 1)
Channel調整変換後　test_data shape:  (10000, 28, 28, 1)


In [7]:
train_data = train_data.astype("float32")
test_data = test_data.astype("float32")
print(test_data)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [8]:
train_data /= 255
test_data /= 255

print("学習データ　train_data shape: ",train_data.shape)
print("学習データ　test_data shape: ",test_data.shape)

学習データ　train_data shape:  (60000, 28, 28, 1)
学習データ　test_data shape:  (10000, 28, 28, 1)


In [9]:
print("Keras変換前学習用教師ラベルデータ　train_teacher_labels shape:", train_teacher_labels.shape)
train_teacher_labels = tf.keras.utils.to_categorical(train_teacher_labels, NUM_CLASSES)
print("Keras変換後学習用教師ラベルデータ　train_teacher_labels shape:", train_teacher_labels.shape)

print("Keras変換前検証用教師ラベルデータ　test_teacher_labels shape:", test_teacher_labels.shape)
print(test_teacher_labels)
test_teacher_labels = tf.keras.utils.to_categorical(test_teacher_labels, NUM_CLASSES)
print("Keras変換後学習用教師ラベルデータ　test_teacher_labels shape:", test_teacher_labels.shape)
print(test_teacher_labels)

Keras変換前学習用教師ラベルデータ　train_teacher_labels shape: (60000,)
Keras変換後学習用教師ラベルデータ　train_teacher_labels shape: (60000, 10)
Keras変換前検証用教師ラベルデータ　test_teacher_labels shape: (10000,)
[7 2 1 ... 4 5 6]
Keras変換後学習用教師ラベルデータ　test_teacher_labels shape: (10000, 10)
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [10]:
Sequential = tf.keras.models.Sequential
model = Sequential()

In [11]:
Dense = tf.keras.layers.Dense
Dropout = tf.keras.layers.Dropout
Flatten = tf.keras.layers.Flatten
Conv2D = tf.keras.layers.Conv2D
MaxPooling2D = tf.keras.layers.MaxPooling2D

In [12]:
model.add(Conv2D(32,kernel_size=(3,3),
                activation="relu",
                input_shape=input_shape))
model.add(Conv2D(64,(3,3),activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128,activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(NUM_CLASSES, activation="softmax"))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 24, 24, 64)        18496     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 12, 12, 64)        0         
_________________________________________________________________
dropout (Dropout)            (None, 12, 12, 64)        0         
_________________________________________________________________
flatten (Flatten)            (None, 9216)              0         
_________________________________________________________________
dense (Dense)                (None, 128)               1179776   
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)               0